### ISSUE TITLE
not display font

### ISSUE THREAD

**Issue by vfa-gianglt-hcm** [blcsntb/mac-setup#2]
Thank you for a good job, but I don't see the font, can you fix?

![screen shot 2018-11-27 at 12 01 00 pm](https://user-images.githubusercontent.com/17284180/49070379-16e8c000-f25e-11e8-95bf-7e21d3cabe96.png)

**Comment by binhapp** [comment]
@vfa-gianglt-hcm We don't support for Terminal.app. Please using [iTerm2](https://www.iterm2.com) instead. Thank you.
